<?php $scriptString = <<<script
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'gr4vy'
            };
            layout([
                {
                    component: 'Magento_Checkout/js/view/payment/default',
                    name: 'payment_method_gr4vy',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);

            $('body').trigger('contentUpdated');
        })
    })
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
